# Generated by Django 3.0.2 on 2020-01-16 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(max_length=50)),
                ('community_description', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField(verbose_name='date created')),
            ],
            options={
                'verbose_name_plural': 'community',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50)),
                ('post_description', models.CharField(max_length=150)),
                ('post_date', models.DateTimeField(verbose_name='post date')),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powwow_api.Community')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powwow_api.User')),
            ],
            options={
                'verbose_name_plural': 'posts',
            },
        ),
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(verbose_name='date joined')),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powwow_api.Community')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powwow_api.User')),
            ],
            options={
                'verbose_name_plural': 'community_member',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=150)),
                ('comment_date', models.DateTimeField(verbose_name='comment date')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powwow_api.Post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powwow_api.User')),
            ],
            options={
                'verbose_name_plural': 'comments',
            },
        ),
    ]
