# Generated by Django 3.0.2 on 2020-01-23 03:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powwow_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(through='powwow_api.CommunityMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
