# Generated by Django 3.0.2 on 2020-01-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powwow_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
