# Generated by Django 3.0.2 on 2020-01-16 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powwow_api', '0002_auto_20200115_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(verbose_name='date published')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powwow_api.User')),
            ],
        ),
    ]
