# Generated by Django 3.0.2 on 2020-01-23 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powwow_api', '0002_community_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitymember',
            old_name='cm',
            new_name='community',
        ),
    ]
