# Generated by Django 3.0.2 on 2020-01-16 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powwow_api', '0003_communities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Communities',
            new_name='Community',
        ),
    ]
