# Generated by Django 3.0.2 on 2020-01-16 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powwow_api', '0004_auto_20200116_0230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name_plural': 'community'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='community',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='community',
            name='user_id',
        ),
        migrations.AddField(
            model_name='community',
            name='community_description',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='community_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='community',
            name='date_created',
            field=models.DateTimeField(default=None, verbose_name='date created'),
        ),
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(verbose_name='date published')),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powwow_api.Community')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powwow_api.User')),
            ],
            options={
                'verbose_name_plural': 'community_member',
            },
        ),
    ]
