# Generated by Django 3.0.2 on 2020-01-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powwow_api', '0004_auto_20200123_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='community',
            field=models.ManyToManyField(through='powwow_api.CommunityMember', to='powwow_api.Community'),
        ),
    ]
