# Generated by Django 3.0.2 on 2020-01-23 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powwow_api', '0005_auto_20200123_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cm',
            new_name='community',
        ),
    ]
