# Generated by Django 3.0.2 on 2020-01-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powwow_api', '0005_auto_20200116_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='community_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
