# Generated by Django 3.0.2 on 2020-01-23 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powwow_api', '0006_auto_20200123_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='community',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='powwow_api.Community'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
