version: '3'

services:
    app:
        container_name: backend_django_server
        build:
            context: ./backend
        ports:
            - "8000:8000"
        volumes:
            - ./backend/app:/app
        command: >
            sh -c "python manage.py runserver 0:8000"
        depends_on:
            - db
    db:
        container_name:  backend_django_database
        image: postgres:12.1-alpine
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
    react:
        container_name: frontend_react_app
        build:
            context: ./frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
        command: >
            sh -c "npm start"
volumes:
    postgres_data: