version: '3'

services:
    app:
        container_name: django_server
        build:
            context: ./backend
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/usr/src/app
        command: >
            sh -c "python manage.py runserver 0:8000"
        depends_on:
            - db
    db:
        container_name: django_server_database
        image: postgres:10.1-alpine
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
volumes:
    postgres_data: